/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_SLASH_GT = 5,
  anon_sym_EQ = 6,
  sym_html_attribute_name = 7,
  sym_html_attribute_value = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_html_quoted_attribute_value_token1 = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_html_quoted_attribute_value_token2 = 12,
  anon_sym_LT_BANG = 13,
  aux_sym_html_doctype_token1 = 14,
  sym__doctype = 15,
  anon_sym_LBRACE_PERCENT = 16,
  anon_sym_PERCENT_RBRACE = 17,
  anon_sym_block = 18,
  anon_sym_endblock = 19,
  anon_sym_if = 20,
  anon_sym_endif = 21,
  sym_variable = 22,
  sym_function_identifier = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  aux_sym_html_entity_token1 = 26,
  aux_sym_html_entity_token2 = 27,
  aux_sym_html_entity_token3 = 28,
  sym_twig_comment = 29,
  anon_sym_LBRACE_LBRACE = 30,
  anon_sym_RBRACE_RBRACE = 31,
  sym__start_tag_name = 32,
  sym__style_start_tag_name = 33,
  sym__end_tag_name = 34,
  sym_erroneous_end_tag_name = 35,
  sym__implicit_end_tag = 36,
  sym_raw_text = 37,
  sym_comment = 38,
  sym__interpolation_content = 39,
  sym_template = 40,
  sym_content = 41,
  sym_html_element = 42,
  sym_style_element = 43,
  sym_style_start_tag = 44,
  sym_html_void_tag = 45,
  sym__node = 46,
  sym_html_start_tag = 47,
  sym_html_end_tag = 48,
  sym_html_self_closing_tag = 49,
  sym_erroneous_end_tag = 50,
  sym_html_attribute = 51,
  sym_html_quoted_attribute_value = 52,
  sym_html_doctype = 53,
  sym_statement_directive = 54,
  sym_if_statement = 55,
  sym_tag_statement = 56,
  sym_tag = 57,
  sym_conditional = 58,
  sym_function_call = 59,
  sym_arguments = 60,
  sym_html_entity = 61,
  sym_vue_interpolation = 62,
  aux_sym_template_repeat1 = 63,
  aux_sym_html_element_repeat1 = 64,
  aux_sym_style_start_tag_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_EQ] = "=",
  [sym_html_attribute_name] = "html_attribute_name",
  [sym_html_attribute_value] = "html_attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_html_quoted_attribute_value_token1] = "html_attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_html_quoted_attribute_value_token2] = "html_attribute_value",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_html_doctype_token1] = "html_doctype_token1",
  [sym__doctype] = "doctype",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_block] = "block",
  [anon_sym_endblock] = "endblock",
  [anon_sym_if] = "if",
  [anon_sym_endif] = "endif",
  [sym_variable] = "variable",
  [sym_function_identifier] = "function_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_html_entity_token1] = "html_entity_token1",
  [aux_sym_html_entity_token2] = "html_entity_token2",
  [aux_sym_html_entity_token3] = "html_entity_token3",
  [sym_twig_comment] = "twig_comment",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym__start_tag_name] = "html_tag_name",
  [sym__style_start_tag_name] = "html_tag_name",
  [sym__end_tag_name] = "html_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym__interpolation_content] = "interpolation_content",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_html_element] = "html_element",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "html_start_tag",
  [sym_html_void_tag] = "html_void_tag",
  [sym__node] = "_node",
  [sym_html_start_tag] = "html_start_tag",
  [sym_html_end_tag] = "html_end_tag",
  [sym_html_self_closing_tag] = "html_self_closing_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_html_attribute] = "html_attribute",
  [sym_html_quoted_attribute_value] = "html_quoted_attribute_value",
  [sym_html_doctype] = "html_doctype",
  [sym_statement_directive] = "statement_directive",
  [sym_if_statement] = "if_statement",
  [sym_tag_statement] = "tag_statement",
  [sym_tag] = "tag",
  [sym_conditional] = "conditional",
  [sym_function_call] = "function_call",
  [sym_arguments] = "arguments",
  [sym_html_entity] = "html_entity",
  [sym_vue_interpolation] = "vue_interpolation",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_html_element_repeat1] = "html_element_repeat1",
  [aux_sym_style_start_tag_repeat1] = "style_start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_html_attribute_name] = sym_html_attribute_name,
  [sym_html_attribute_value] = sym_html_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_html_quoted_attribute_value_token1] = sym_html_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_html_quoted_attribute_value_token2] = sym_html_attribute_value,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_html_doctype_token1] = aux_sym_html_doctype_token1,
  [sym__doctype] = sym__doctype,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_endblock] = anon_sym_endblock,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_endif] = anon_sym_endif,
  [sym_variable] = sym_variable,
  [sym_function_identifier] = sym_function_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_html_entity_token1] = aux_sym_html_entity_token1,
  [aux_sym_html_entity_token2] = aux_sym_html_entity_token2,
  [aux_sym_html_entity_token3] = aux_sym_html_entity_token3,
  [sym_twig_comment] = sym_twig_comment,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym__interpolation_content] = sym__interpolation_content,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_html_element] = sym_html_element,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_html_start_tag,
  [sym_html_void_tag] = sym_html_void_tag,
  [sym__node] = sym__node,
  [sym_html_start_tag] = sym_html_start_tag,
  [sym_html_end_tag] = sym_html_end_tag,
  [sym_html_self_closing_tag] = sym_html_self_closing_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_html_attribute] = sym_html_attribute,
  [sym_html_quoted_attribute_value] = sym_html_quoted_attribute_value,
  [sym_html_doctype] = sym_html_doctype,
  [sym_statement_directive] = sym_statement_directive,
  [sym_if_statement] = sym_if_statement,
  [sym_tag_statement] = sym_tag_statement,
  [sym_tag] = sym_tag,
  [sym_conditional] = sym_conditional,
  [sym_function_call] = sym_function_call,
  [sym_arguments] = sym_arguments,
  [sym_html_entity] = sym_html_entity,
  [sym_vue_interpolation] = sym_vue_interpolation,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_html_element_repeat1] = aux_sym_html_element_repeat1,
  [aux_sym_style_start_tag_repeat1] = aux_sym_style_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_html_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_html_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endblock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_entity_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_entity_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_entity_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_twig_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_html_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_void_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_html_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_html_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_html_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_html_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_vue_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_style_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 21,
  [28] = 28,
  [29] = 9,
  [30] = 22,
  [31] = 11,
  [32] = 13,
  [33] = 14,
  [34] = 16,
  [35] = 19,
  [36] = 15,
  [37] = 23,
  [38] = 10,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 39,
  [43] = 40,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 41,
  [49] = 45,
  [50] = 50,
  [51] = 51,
  [52] = 47,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 51,
  [65] = 53,
  [66] = 56,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 70,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 88,
  [89] = 75,
  [90] = 78,
  [91] = 83,
  [92] = 69,
  [93] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 49,
        '%', 25,
        '&', 2,
        '\'', 52,
        '(', 84,
        ')', 85,
        '/', 10,
        '<', 42,
        '=', 46,
        '>', 43,
        'b', 20,
        'e', 22,
        'i', 16,
        '{', 3,
        '}', 26,
        'D', 30,
        'd', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '\'') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead == '{') ADVANCE(90);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '>') ADVANCE(43);
      if (lookahead == '#' ||
          lookahead == ':' ||
          lookahead == '@') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == ';') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ';') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == ';') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'b') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(80);
      if (lookahead == 'i') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(65);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(67);
      END_STATE();
    case 18:
      if (lookahead == 'k') ADVANCE(61);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(60);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(91);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(89);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 28:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 29:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 31:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 34:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 38:
      if (('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(55);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_html_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x1f4a9) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_html_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_html_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_html_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_block);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_endblock);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_endblock);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_endif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'b') ADVANCE(79);
      if (lookahead == 'i') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'c') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'c') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'd') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'f') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'k') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'k') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'l') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'l') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'n') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'o') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_function_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_html_entity_token1);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_html_entity_token2);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_html_entity_token3);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_twig_comment);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39, .external_lex_state = 2},
  [5] = {.lex_state = 39, .external_lex_state = 2},
  [6] = {.lex_state = 39, .external_lex_state = 2},
  [7] = {.lex_state = 39, .external_lex_state = 2},
  [8] = {.lex_state = 39, .external_lex_state = 2},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 39},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 39},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 39, .external_lex_state = 2},
  [27] = {.lex_state = 39, .external_lex_state = 2},
  [28] = {.lex_state = 39, .external_lex_state = 2},
  [29] = {.lex_state = 39, .external_lex_state = 2},
  [30] = {.lex_state = 39, .external_lex_state = 2},
  [31] = {.lex_state = 39, .external_lex_state = 2},
  [32] = {.lex_state = 39, .external_lex_state = 2},
  [33] = {.lex_state = 39, .external_lex_state = 2},
  [34] = {.lex_state = 39, .external_lex_state = 2},
  [35] = {.lex_state = 39, .external_lex_state = 2},
  [36] = {.lex_state = 39, .external_lex_state = 2},
  [37] = {.lex_state = 39, .external_lex_state = 2},
  [38] = {.lex_state = 39, .external_lex_state = 2},
  [39] = {.lex_state = 6, .external_lex_state = 3},
  [40] = {.lex_state = 6, .external_lex_state = 3},
  [41] = {.lex_state = 6, .external_lex_state = 3},
  [42] = {.lex_state = 6, .external_lex_state = 3},
  [43] = {.lex_state = 6, .external_lex_state = 3},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6, .external_lex_state = 3},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 6, .external_lex_state = 3},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6, .external_lex_state = 3},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 6},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0, .external_lex_state = 7},
  [69] = {.lex_state = 50},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 53},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 36},
  [83] = {.lex_state = 0, .external_lex_state = 8},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 9},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 50},
  [93] = {.lex_state = 53},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_endblock] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_html_entity_token1] = ACTIONS(1),
    [aux_sym_html_entity_token2] = ACTIONS(1),
    [aux_sym_html_entity_token3] = ACTIONS(1),
    [sym_twig_comment] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__interpolation_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(85),
    [sym_content] = STATE(3),
    [sym_html_element] = STATE(3),
    [sym_style_element] = STATE(3),
    [sym_style_start_tag] = STATE(50),
    [sym_html_void_tag] = STATE(22),
    [sym_html_start_tag] = STATE(5),
    [sym_html_self_closing_tag] = STATE(22),
    [sym_erroneous_end_tag] = STATE(3),
    [sym_html_doctype] = STATE(3),
    [sym_statement_directive] = STATE(3),
    [sym_html_entity] = STATE(3),
    [sym_vue_interpolation] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_SLASH] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(11),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(13),
    [aux_sym_html_entity_token1] = ACTIONS(15),
    [aux_sym_html_entity_token2] = ACTIONS(15),
    [aux_sym_html_entity_token3] = ACTIONS(15),
    [sym_twig_comment] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      aux_sym_content_token1,
    ACTIONS(26), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(32), 1,
      anon_sym_LT_BANG,
    ACTIONS(35), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(41), 1,
      sym_twig_comment,
    ACTIONS(44), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(5), 1,
      sym_html_start_tag,
    STATE(50), 1,
      sym_style_start_tag,
    STATE(22), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(38), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(2), 9,
      sym_content,
      sym_html_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_html_doctype,
      sym_statement_directive,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_template_repeat1,
  [51] = 13,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(11), 1,
      anon_sym_LT_BANG,
    ACTIONS(13), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(19), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_twig_comment,
    STATE(5), 1,
      sym_html_start_tag,
    STATE(50), 1,
      sym_style_start_tag,
    STATE(22), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(15), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(2), 9,
      sym_content,
      sym_html_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_html_doctype,
      sym_statement_directive,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_template_repeat1,
  [102] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(59), 1,
      sym_twig_comment,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(63), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(15), 1,
      sym_html_end_tag,
    STATE(30), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [144] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      sym_twig_comment,
    ACTIONS(67), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(14), 1,
      sym_html_end_tag,
    STATE(30), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(4), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [186] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      sym_twig_comment,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LT_SLASH,
    ACTIONS(71), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(36), 1,
      sym_html_end_tag,
    STATE(30), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [228] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LT_SLASH,
    ACTIONS(73), 1,
      sym_twig_comment,
    ACTIONS(75), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(33), 1,
      sym_html_end_tag,
    STATE(30), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(6), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [270] = 9,
    ACTIONS(77), 1,
      aux_sym_content_token1,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_twig_comment,
    ACTIONS(91), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(7), 1,
      sym_html_start_tag,
    ACTIONS(83), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
    STATE(30), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(85), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [307] = 2,
    ACTIONS(96), 1,
      anon_sym_LT,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [323] = 2,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(98), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [339] = 2,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(102), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [355] = 2,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(106), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [371] = 2,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [387] = 2,
    ACTIONS(118), 1,
      anon_sym_LT,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [403] = 2,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [419] = 2,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [435] = 2,
    ACTIONS(130), 1,
      anon_sym_LT,
    ACTIONS(128), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [451] = 2,
    ACTIONS(134), 1,
      anon_sym_LT,
    ACTIONS(132), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [467] = 2,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [483] = 2,
    ACTIONS(142), 1,
      anon_sym_LT,
    ACTIONS(140), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [499] = 2,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [515] = 2,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [531] = 2,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(152), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [547] = 2,
    ACTIONS(158), 1,
      anon_sym_LT,
    ACTIONS(156), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [563] = 6,
    ACTIONS(164), 1,
      sym_function_identifier,
    STATE(58), 1,
      sym_tag,
    STATE(60), 1,
      sym_conditional,
    ACTIONS(160), 2,
      anon_sym_block,
      anon_sym_endblock,
    ACTIONS(162), 2,
      anon_sym_if,
      anon_sym_endif,
    STATE(80), 3,
      sym_if_statement,
      sym_tag_statement,
      sym_function_call,
  [586] = 2,
    ACTIONS(168), 1,
      anon_sym_LT,
    ACTIONS(166), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [600] = 2,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [614] = 2,
    ACTIONS(172), 1,
      anon_sym_LT,
    ACTIONS(170), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [628] = 2,
    ACTIONS(96), 1,
      anon_sym_LT,
    ACTIONS(94), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [642] = 2,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [656] = 2,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(102), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [670] = 2,
    ACTIONS(113), 1,
      anon_sym_LT,
    ACTIONS(110), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [684] = 2,
    ACTIONS(118), 1,
      anon_sym_LT,
    ACTIONS(116), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [698] = 2,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(124), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [712] = 2,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [726] = 2,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [740] = 2,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(152), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [754] = 2,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(98), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [768] = 4,
    ACTIONS(174), 1,
      anon_sym_GT,
    ACTIONS(176), 1,
      anon_sym_SLASH_GT,
    ACTIONS(178), 1,
      sym_html_attribute_name,
    STATE(40), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [782] = 4,
    ACTIONS(178), 1,
      sym_html_attribute_name,
    ACTIONS(180), 1,
      anon_sym_GT,
    ACTIONS(182), 1,
      anon_sym_SLASH_GT,
    STATE(41), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [796] = 3,
    ACTIONS(186), 1,
      sym_html_attribute_name,
    ACTIONS(184), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(41), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [808] = 4,
    ACTIONS(174), 1,
      anon_sym_GT,
    ACTIONS(178), 1,
      sym_html_attribute_name,
    ACTIONS(189), 1,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [822] = 4,
    ACTIONS(178), 1,
      sym_html_attribute_name,
    ACTIONS(180), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      anon_sym_SLASH_GT,
    STATE(41), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [836] = 3,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      sym_html_attribute_name,
    STATE(46), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [847] = 4,
    ACTIONS(197), 1,
      sym_html_attribute_value,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
    STATE(51), 1,
      sym_html_quoted_attribute_value,
  [860] = 3,
    ACTIONS(195), 1,
      sym_html_attribute_name,
    ACTIONS(203), 1,
      anon_sym_GT,
    STATE(48), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [871] = 2,
    ACTIONS(207), 1,
      anon_sym_EQ,
    ACTIONS(205), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [880] = 3,
    ACTIONS(184), 1,
      anon_sym_GT,
    ACTIONS(209), 1,
      sym_html_attribute_name,
    STATE(48), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [891] = 4,
    ACTIONS(212), 1,
      sym_html_attribute_value,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    ACTIONS(216), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_html_quoted_attribute_value,
  [904] = 3,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(218), 1,
      sym_raw_text,
    STATE(12), 1,
      sym_html_end_tag,
  [914] = 1,
    ACTIONS(220), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [920] = 2,
    ACTIONS(222), 1,
      anon_sym_EQ,
    ACTIONS(205), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [928] = 1,
    ACTIONS(224), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [934] = 1,
    ACTIONS(226), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [939] = 2,
    ACTIONS(228), 1,
      anon_sym_LPAREN,
    STATE(74), 1,
      sym_arguments,
  [946] = 2,
    ACTIONS(230), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(232), 1,
      sym__interpolation_content,
  [953] = 1,
    ACTIONS(234), 2,
      anon_sym_PERCENT_RBRACE,
      sym_variable,
  [958] = 2,
    ACTIONS(236), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(238), 1,
      sym_variable,
  [965] = 1,
    ACTIONS(240), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [970] = 2,
    ACTIONS(236), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(242), 1,
      sym_variable,
  [977] = 1,
    ACTIONS(244), 2,
      anon_sym_PERCENT_RBRACE,
      sym_variable,
  [982] = 2,
    ACTIONS(246), 1,
      sym__start_tag_name,
    ACTIONS(248), 1,
      sym__style_start_tag_name,
  [989] = 2,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    STATE(20), 1,
      sym_html_end_tag,
  [996] = 1,
    ACTIONS(220), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [1001] = 1,
    ACTIONS(224), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [1006] = 2,
    ACTIONS(250), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(252), 1,
      sym__interpolation_content,
  [1013] = 1,
    ACTIONS(254), 1,
      anon_sym_GT,
  [1017] = 1,
    ACTIONS(256), 1,
      sym__start_tag_name,
  [1021] = 1,
    ACTIONS(258), 1,
      aux_sym_html_quoted_attribute_value_token1,
  [1025] = 1,
    ACTIONS(260), 1,
      anon_sym_RBRACE_RBRACE,
  [1029] = 1,
    ACTIONS(262), 1,
      anon_sym_GT,
  [1033] = 1,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
  [1037] = 1,
    ACTIONS(266), 1,
      aux_sym_html_quoted_attribute_value_token2,
  [1041] = 1,
    ACTIONS(268), 1,
      anon_sym_PERCENT_RBRACE,
  [1045] = 1,
    ACTIONS(270), 1,
      anon_sym_DQUOTE,
  [1049] = 1,
    ACTIONS(272), 1,
      anon_sym_PERCENT_RBRACE,
  [1053] = 1,
    ACTIONS(274), 1,
      anon_sym_PERCENT_RBRACE,
  [1057] = 1,
    ACTIONS(270), 1,
      anon_sym_SQUOTE,
  [1061] = 1,
    ACTIONS(276), 1,
      anon_sym_PERCENT_RBRACE,
  [1065] = 1,
    ACTIONS(278), 1,
      anon_sym_PERCENT_RBRACE,
  [1069] = 1,
    ACTIONS(280), 1,
      sym__doctype,
  [1073] = 1,
    ACTIONS(282), 1,
      aux_sym_html_doctype_token1,
  [1077] = 1,
    ACTIONS(284), 1,
      sym__end_tag_name,
  [1081] = 1,
    ACTIONS(286), 1,
      anon_sym_RBRACE_RBRACE,
  [1085] = 1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
  [1089] = 1,
    ACTIONS(290), 1,
      anon_sym_GT,
  [1093] = 1,
    ACTIONS(292), 1,
      anon_sym_GT,
  [1097] = 1,
    ACTIONS(294), 1,
      sym_erroneous_end_tag_name,
  [1101] = 1,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
  [1105] = 1,
    ACTIONS(296), 1,
      anon_sym_SQUOTE,
  [1109] = 1,
    ACTIONS(298), 1,
      sym__end_tag_name,
  [1113] = 1,
    ACTIONS(300), 1,
      aux_sym_html_quoted_attribute_value_token1,
  [1117] = 1,
    ACTIONS(302), 1,
      aux_sym_html_quoted_attribute_value_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 228,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 307,
  [SMALL_STATE(10)] = 323,
  [SMALL_STATE(11)] = 339,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 371,
  [SMALL_STATE(14)] = 387,
  [SMALL_STATE(15)] = 403,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 435,
  [SMALL_STATE(18)] = 451,
  [SMALL_STATE(19)] = 467,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 499,
  [SMALL_STATE(22)] = 515,
  [SMALL_STATE(23)] = 531,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 563,
  [SMALL_STATE(26)] = 586,
  [SMALL_STATE(27)] = 600,
  [SMALL_STATE(28)] = 614,
  [SMALL_STATE(29)] = 628,
  [SMALL_STATE(30)] = 642,
  [SMALL_STATE(31)] = 656,
  [SMALL_STATE(32)] = 670,
  [SMALL_STATE(33)] = 684,
  [SMALL_STATE(34)] = 698,
  [SMALL_STATE(35)] = 712,
  [SMALL_STATE(36)] = 726,
  [SMALL_STATE(37)] = 740,
  [SMALL_STATE(38)] = 754,
  [SMALL_STATE(39)] = 768,
  [SMALL_STATE(40)] = 782,
  [SMALL_STATE(41)] = 796,
  [SMALL_STATE(42)] = 808,
  [SMALL_STATE(43)] = 822,
  [SMALL_STATE(44)] = 836,
  [SMALL_STATE(45)] = 847,
  [SMALL_STATE(46)] = 860,
  [SMALL_STATE(47)] = 871,
  [SMALL_STATE(48)] = 880,
  [SMALL_STATE(49)] = 891,
  [SMALL_STATE(50)] = 904,
  [SMALL_STATE(51)] = 914,
  [SMALL_STATE(52)] = 920,
  [SMALL_STATE(53)] = 928,
  [SMALL_STATE(54)] = 934,
  [SMALL_STATE(55)] = 939,
  [SMALL_STATE(56)] = 946,
  [SMALL_STATE(57)] = 953,
  [SMALL_STATE(58)] = 958,
  [SMALL_STATE(59)] = 965,
  [SMALL_STATE(60)] = 970,
  [SMALL_STATE(61)] = 977,
  [SMALL_STATE(62)] = 982,
  [SMALL_STATE(63)] = 989,
  [SMALL_STATE(64)] = 996,
  [SMALL_STATE(65)] = 1001,
  [SMALL_STATE(66)] = 1006,
  [SMALL_STATE(67)] = 1013,
  [SMALL_STATE(68)] = 1017,
  [SMALL_STATE(69)] = 1021,
  [SMALL_STATE(70)] = 1025,
  [SMALL_STATE(71)] = 1029,
  [SMALL_STATE(72)] = 1033,
  [SMALL_STATE(73)] = 1037,
  [SMALL_STATE(74)] = 1041,
  [SMALL_STATE(75)] = 1045,
  [SMALL_STATE(76)] = 1049,
  [SMALL_STATE(77)] = 1053,
  [SMALL_STATE(78)] = 1057,
  [SMALL_STATE(79)] = 1061,
  [SMALL_STATE(80)] = 1065,
  [SMALL_STATE(81)] = 1069,
  [SMALL_STATE(82)] = 1073,
  [SMALL_STATE(83)] = 1077,
  [SMALL_STATE(84)] = 1081,
  [SMALL_STATE(85)] = 1085,
  [SMALL_STATE(86)] = 1089,
  [SMALL_STATE(87)] = 1093,
  [SMALL_STATE(88)] = 1097,
  [SMALL_STATE(89)] = 1101,
  [SMALL_STATE(90)] = 1105,
  [SMALL_STATE(91)] = 1109,
  [SMALL_STATE(92)] = 1113,
  [SMALL_STATE(93)] = 1117,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_entity, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_entity, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vue_interpolation, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vue_interpolation, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0), REDUCE(sym_html_void_tag, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0), REDUCE(sym_html_void_tag, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_self_closing_tag, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_self_closing_tag, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_directive, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_directive, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vue_interpolation, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vue_interpolation, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_self_closing_tag, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_self_closing_tag, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_doctype, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_doctype, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attribute, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attribute, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_quoted_attribute_value, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_statement, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_statement, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [288] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__style_start_tag_name = 1,
  ts_external_token__end_tag_name = 2,
  ts_external_token_erroneous_end_tag_name = 3,
  ts_external_token_SLASH_GT = 4,
  ts_external_token__implicit_end_tag = 5,
  ts_external_token_raw_text = 6,
  ts_external_token_comment = 7,
  ts_external_token__interpolation_content = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token__interpolation_content] = sym__interpolation_content,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_content] = true,
  },
  [2] = {
    [ts_external_token__implicit_end_tag] = true,
  },
  [3] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [4] = {
    [ts_external_token_raw_text] = true,
  },
  [5] = {
    [ts_external_token__interpolation_content] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_shopware_twig_external_scanner_create(void);
void tree_sitter_shopware_twig_external_scanner_destroy(void *);
bool tree_sitter_shopware_twig_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_shopware_twig_external_scanner_serialize(void *, char *);
void tree_sitter_shopware_twig_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shopware_twig(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_shopware_twig_external_scanner_create,
      tree_sitter_shopware_twig_external_scanner_destroy,
      tree_sitter_shopware_twig_external_scanner_scan,
      tree_sitter_shopware_twig_external_scanner_serialize,
      tree_sitter_shopware_twig_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "shopware_twig",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
