/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_SLASH_GT = 5,
  anon_sym_EQ = 6,
  sym_html_attribute_name = 7,
  sym_html_attribute_value = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_html_quoted_attribute_value_token1 = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_html_quoted_attribute_value_token2 = 12,
  anon_sym_LT_BANG = 13,
  aux_sym_html_doctype_token1 = 14,
  sym__doctype = 15,
  anon_sym_LBRACE_PERCENT = 16,
  anon_sym_PERCENT_RBRACE = 17,
  anon_sym_block = 18,
  anon_sym_endblock = 19,
  anon_sym_if = 20,
  anon_sym_endif = 21,
  sym_variable = 22,
  sym_function_identifier = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  aux_sym_html_entity_token1 = 26,
  aux_sym_html_entity_token2 = 27,
  aux_sym_html_entity_token3 = 28,
  sym_twig_comment = 29,
  anon_sym_LBRACE_LBRACE = 30,
  anon_sym_RBRACE_RBRACE = 31,
  sym__start_tag_name = 32,
  sym__style_start_tag_name = 33,
  sym__script_start_tag_name = 34,
  sym__end_tag_name = 35,
  sym_erroneous_end_tag_name = 36,
  sym__implicit_end_tag = 37,
  sym_raw_text = 38,
  sym_comment = 39,
  sym__interpolation_content = 40,
  sym_template = 41,
  sym_content = 42,
  sym_html_element = 43,
  sym_style_element = 44,
  sym_style_start_tag = 45,
  sym_script_element = 46,
  sym_script_start_tag = 47,
  sym_html_void_tag = 48,
  sym__node = 49,
  sym_html_start_tag = 50,
  sym_html_end_tag = 51,
  sym_html_self_closing_tag = 52,
  sym_erroneous_end_tag = 53,
  sym_html_attribute = 54,
  sym_html_quoted_attribute_value = 55,
  sym_html_doctype = 56,
  sym_statement_directive = 57,
  sym_if_statement = 58,
  sym_tag_statement = 59,
  sym_tag = 60,
  sym_conditional = 61,
  sym_function_call = 62,
  sym_arguments = 63,
  sym_html_entity = 64,
  sym_vue_interpolation = 65,
  aux_sym_template_repeat1 = 66,
  aux_sym_html_element_repeat1 = 67,
  aux_sym_style_start_tag_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_EQ] = "=",
  [sym_html_attribute_name] = "html_attribute_name",
  [sym_html_attribute_value] = "html_attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_html_quoted_attribute_value_token1] = "html_attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_html_quoted_attribute_value_token2] = "html_attribute_value",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_html_doctype_token1] = "html_doctype_token1",
  [sym__doctype] = "doctype",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_block] = "block",
  [anon_sym_endblock] = "endblock",
  [anon_sym_if] = "if",
  [anon_sym_endif] = "endif",
  [sym_variable] = "variable",
  [sym_function_identifier] = "function_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_html_entity_token1] = "html_entity_token1",
  [aux_sym_html_entity_token2] = "html_entity_token2",
  [aux_sym_html_entity_token3] = "html_entity_token3",
  [sym_twig_comment] = "twig_comment",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym__start_tag_name] = "html_tag_name",
  [sym__style_start_tag_name] = "html_tag_name",
  [sym__script_start_tag_name] = "html_tag_name",
  [sym__end_tag_name] = "html_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym__interpolation_content] = "interpolation_content",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_html_element] = "html_element",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "html_start_tag",
  [sym_script_element] = "script_element",
  [sym_script_start_tag] = "html_start_tag",
  [sym_html_void_tag] = "html_void_tag",
  [sym__node] = "_node",
  [sym_html_start_tag] = "html_start_tag",
  [sym_html_end_tag] = "html_end_tag",
  [sym_html_self_closing_tag] = "html_self_closing_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_html_attribute] = "html_attribute",
  [sym_html_quoted_attribute_value] = "html_quoted_attribute_value",
  [sym_html_doctype] = "html_doctype",
  [sym_statement_directive] = "statement_directive",
  [sym_if_statement] = "if_statement",
  [sym_tag_statement] = "tag_statement",
  [sym_tag] = "tag",
  [sym_conditional] = "conditional",
  [sym_function_call] = "function_call",
  [sym_arguments] = "arguments",
  [sym_html_entity] = "html_entity",
  [sym_vue_interpolation] = "vue_interpolation",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_html_element_repeat1] = "html_element_repeat1",
  [aux_sym_style_start_tag_repeat1] = "style_start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_html_attribute_name] = sym_html_attribute_name,
  [sym_html_attribute_value] = sym_html_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_html_quoted_attribute_value_token1] = sym_html_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_html_quoted_attribute_value_token2] = sym_html_attribute_value,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_html_doctype_token1] = aux_sym_html_doctype_token1,
  [sym__doctype] = sym__doctype,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_endblock] = anon_sym_endblock,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_endif] = anon_sym_endif,
  [sym_variable] = sym_variable,
  [sym_function_identifier] = sym_function_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_html_entity_token1] = aux_sym_html_entity_token1,
  [aux_sym_html_entity_token2] = aux_sym_html_entity_token2,
  [aux_sym_html_entity_token3] = aux_sym_html_entity_token3,
  [sym_twig_comment] = sym_twig_comment,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym__interpolation_content] = sym__interpolation_content,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_html_element] = sym_html_element,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_html_start_tag,
  [sym_script_element] = sym_script_element,
  [sym_script_start_tag] = sym_html_start_tag,
  [sym_html_void_tag] = sym_html_void_tag,
  [sym__node] = sym__node,
  [sym_html_start_tag] = sym_html_start_tag,
  [sym_html_end_tag] = sym_html_end_tag,
  [sym_html_self_closing_tag] = sym_html_self_closing_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_html_attribute] = sym_html_attribute,
  [sym_html_quoted_attribute_value] = sym_html_quoted_attribute_value,
  [sym_html_doctype] = sym_html_doctype,
  [sym_statement_directive] = sym_statement_directive,
  [sym_if_statement] = sym_if_statement,
  [sym_tag_statement] = sym_tag_statement,
  [sym_tag] = sym_tag,
  [sym_conditional] = sym_conditional,
  [sym_function_call] = sym_function_call,
  [sym_arguments] = sym_arguments,
  [sym_html_entity] = sym_html_entity,
  [sym_vue_interpolation] = sym_vue_interpolation,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_html_element_repeat1] = aux_sym_html_element_repeat1,
  [aux_sym_style_start_tag_repeat1] = aux_sym_style_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_html_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_html_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endblock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_html_entity_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_entity_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_entity_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_twig_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_html_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_void_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_html_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_html_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_html_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_html_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_vue_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_style_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 10,
  [31] = 19,
  [32] = 12,
  [33] = 20,
  [34] = 26,
  [35] = 11,
  [36] = 15,
  [37] = 18,
  [38] = 14,
  [39] = 21,
  [40] = 23,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 48,
  [51] = 42,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 53,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 54,
  [69] = 55,
  [70] = 64,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 77,
  [93] = 93,
  [94] = 94,
  [95] = 86,
  [96] = 96,
  [97] = 89,
  [98] = 90,
  [99] = 96,
  [100] = 87,
  [101] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 49,
        '%', 25,
        '&', 2,
        '\'', 52,
        '(', 84,
        ')', 85,
        '/', 10,
        '<', 42,
        '=', 46,
        '>', 43,
        'b', 20,
        'e', 22,
        'i', 16,
        '{', 3,
        '}', 26,
        'D', 30,
        'd', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '\'') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead == '{') ADVANCE(90);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '>') ADVANCE(43);
      if (lookahead == '#' ||
          lookahead == ':' ||
          lookahead == '@') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == ';') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ';') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == ';') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'b') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(80);
      if (lookahead == 'i') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(65);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(67);
      END_STATE();
    case 18:
      if (lookahead == 'k') ADVANCE(61);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(60);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(91);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(89);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 28:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 29:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 31:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 34:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 38:
      if (('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(55);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_html_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x1f4a9) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_html_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_html_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_html_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_html_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_block);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_endblock);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_endblock);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_endif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'b') ADVANCE(79);
      if (lookahead == 'i') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'c') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'c') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'd') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'f') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'k') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'k') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'l') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'l') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'n') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_function_identifier);
      if (lookahead == 'o') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_function_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_html_entity_token1);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_html_entity_token2);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_html_entity_token3);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_twig_comment);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39, .external_lex_state = 2},
  [5] = {.lex_state = 39, .external_lex_state = 2},
  [6] = {.lex_state = 39, .external_lex_state = 2},
  [7] = {.lex_state = 39, .external_lex_state = 2},
  [8] = {.lex_state = 39, .external_lex_state = 2},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 39},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 39},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 39, .external_lex_state = 2},
  [29] = {.lex_state = 39, .external_lex_state = 2},
  [30] = {.lex_state = 39, .external_lex_state = 2},
  [31] = {.lex_state = 39, .external_lex_state = 2},
  [32] = {.lex_state = 39, .external_lex_state = 2},
  [33] = {.lex_state = 39, .external_lex_state = 2},
  [34] = {.lex_state = 39, .external_lex_state = 2},
  [35] = {.lex_state = 39, .external_lex_state = 2},
  [36] = {.lex_state = 39, .external_lex_state = 2},
  [37] = {.lex_state = 39, .external_lex_state = 2},
  [38] = {.lex_state = 39, .external_lex_state = 2},
  [39] = {.lex_state = 39, .external_lex_state = 2},
  [40] = {.lex_state = 39, .external_lex_state = 2},
  [41] = {.lex_state = 6, .external_lex_state = 3},
  [42] = {.lex_state = 6, .external_lex_state = 3},
  [43] = {.lex_state = 6, .external_lex_state = 3},
  [44] = {.lex_state = 6, .external_lex_state = 3},
  [45] = {.lex_state = 6, .external_lex_state = 3},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6, .external_lex_state = 3},
  [54] = {.lex_state = 6, .external_lex_state = 3},
  [55] = {.lex_state = 6, .external_lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 6},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 6},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0, .external_lex_state = 7},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 36},
  [84] = {.lex_state = 0, .external_lex_state = 8},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 50},
  [88] = {.lex_state = 53},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 9},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0, .external_lex_state = 9},
  [100] = {.lex_state = 50},
  [101] = {.lex_state = 53},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_endblock] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_html_entity_token1] = ACTIONS(1),
    [aux_sym_html_entity_token2] = ACTIONS(1),
    [aux_sym_html_entity_token3] = ACTIONS(1),
    [sym_twig_comment] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__interpolation_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(76),
    [sym_content] = STATE(3),
    [sym_html_element] = STATE(3),
    [sym_style_element] = STATE(3),
    [sym_style_start_tag] = STATE(56),
    [sym_script_element] = STATE(3),
    [sym_script_start_tag] = STATE(57),
    [sym_html_void_tag] = STATE(12),
    [sym_html_start_tag] = STATE(5),
    [sym_html_self_closing_tag] = STATE(12),
    [sym_erroneous_end_tag] = STATE(3),
    [sym_html_doctype] = STATE(3),
    [sym_statement_directive] = STATE(3),
    [sym_html_entity] = STATE(3),
    [sym_vue_interpolation] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_SLASH] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(11),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(13),
    [aux_sym_html_entity_token1] = ACTIONS(15),
    [aux_sym_html_entity_token2] = ACTIONS(15),
    [aux_sym_html_entity_token3] = ACTIONS(15),
    [sym_twig_comment] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      aux_sym_content_token1,
    ACTIONS(26), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(32), 1,
      anon_sym_LT_BANG,
    ACTIONS(35), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(41), 1,
      sym_twig_comment,
    ACTIONS(44), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(5), 1,
      sym_html_start_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(12), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(38), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(2), 10,
      sym_content,
      sym_html_element,
      sym_style_element,
      sym_script_element,
      sym_erroneous_end_tag,
      sym_html_doctype,
      sym_statement_directive,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_template_repeat1,
  [55] = 14,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(11), 1,
      anon_sym_LT_BANG,
    ACTIONS(13), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(19), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_twig_comment,
    STATE(5), 1,
      sym_html_start_tag,
    STATE(56), 1,
      sym_style_start_tag,
    STATE(57), 1,
      sym_script_start_tag,
    STATE(12), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(15), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(2), 10,
      sym_content,
      sym_html_element,
      sym_style_element,
      sym_script_element,
      sym_erroneous_end_tag,
      sym_html_doctype,
      sym_statement_directive,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_template_repeat1,
  [110] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(59), 1,
      sym_twig_comment,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(63), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(38), 1,
      sym_html_end_tag,
    STATE(32), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [152] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_twig_comment,
    ACTIONS(69), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(11), 1,
      sym_html_end_tag,
    STATE(32), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(6), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [194] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      sym_twig_comment,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(71), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(14), 1,
      sym_html_end_tag,
    STATE(32), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [236] = 11,
    ACTIONS(51), 1,
      aux_sym_content_token1,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(73), 1,
      sym_twig_comment,
    ACTIONS(75), 1,
      sym__implicit_end_tag,
    STATE(7), 1,
      sym_html_start_tag,
    STATE(35), 1,
      sym_html_end_tag,
    STATE(32), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(57), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(4), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [278] = 9,
    ACTIONS(77), 1,
      aux_sym_content_token1,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_twig_comment,
    ACTIONS(91), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(7), 1,
      sym_html_start_tag,
    ACTIONS(83), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
    STATE(32), 2,
      sym_html_void_tag,
      sym_html_self_closing_tag,
    ACTIONS(85), 3,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
    STATE(8), 6,
      sym_content,
      sym_html_element,
      sym__node,
      sym_html_entity,
      sym_vue_interpolation,
      aux_sym_html_element_repeat1,
  [315] = 2,
    ACTIONS(96), 1,
      anon_sym_LT,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [331] = 2,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(98), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [347] = 2,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(102), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [363] = 2,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(106), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [379] = 2,
    ACTIONS(112), 1,
      anon_sym_LT,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [395] = 2,
    ACTIONS(116), 1,
      anon_sym_LT,
    ACTIONS(114), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [411] = 2,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(118), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [427] = 2,
    ACTIONS(124), 1,
      anon_sym_LT,
    ACTIONS(122), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [443] = 2,
    ACTIONS(128), 1,
      anon_sym_LT,
    ACTIONS(126), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [459] = 2,
    ACTIONS(132), 1,
      anon_sym_LT,
    ACTIONS(130), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [475] = 2,
    ACTIONS(136), 1,
      anon_sym_LT,
    ACTIONS(134), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [491] = 2,
    ACTIONS(140), 1,
      anon_sym_LT,
    ACTIONS(138), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [507] = 2,
    ACTIONS(144), 1,
      anon_sym_LT,
    ACTIONS(142), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [523] = 2,
    ACTIONS(148), 1,
      anon_sym_LT,
    ACTIONS(146), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [539] = 2,
    ACTIONS(152), 1,
      anon_sym_LT,
    ACTIONS(150), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [555] = 2,
    ACTIONS(156), 1,
      anon_sym_LT,
    ACTIONS(154), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [571] = 2,
    ACTIONS(160), 1,
      anon_sym_LT,
    ACTIONS(158), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [587] = 2,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(162), 10,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG,
      anon_sym_LBRACE_PERCENT,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [603] = 6,
    ACTIONS(172), 1,
      sym_function_identifier,
    STATE(61), 1,
      sym_tag,
    STATE(74), 1,
      sym_conditional,
    ACTIONS(168), 2,
      anon_sym_block,
      anon_sym_endblock,
    ACTIONS(170), 2,
      anon_sym_if,
      anon_sym_endif,
    STATE(93), 3,
      sym_if_statement,
      sym_tag_statement,
      sym_function_call,
  [626] = 2,
    ACTIONS(176), 1,
      anon_sym_LT,
    ACTIONS(174), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [640] = 2,
    ACTIONS(180), 1,
      anon_sym_LT,
    ACTIONS(178), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [654] = 2,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(98), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [668] = 2,
    ACTIONS(136), 1,
      anon_sym_LT,
    ACTIONS(134), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [682] = 2,
    ACTIONS(108), 1,
      anon_sym_LT,
    ACTIONS(106), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [696] = 2,
    ACTIONS(140), 1,
      anon_sym_LT,
    ACTIONS(138), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [710] = 2,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(162), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [724] = 2,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(102), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [738] = 2,
    ACTIONS(120), 1,
      anon_sym_LT,
    ACTIONS(118), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [752] = 2,
    ACTIONS(132), 1,
      anon_sym_LT,
    ACTIONS(130), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [766] = 2,
    ACTIONS(116), 1,
      anon_sym_LT,
    ACTIONS(114), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [780] = 2,
    ACTIONS(144), 1,
      anon_sym_LT,
    ACTIONS(142), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [794] = 2,
    ACTIONS(152), 1,
      anon_sym_LT,
    ACTIONS(150), 8,
      sym__implicit_end_tag,
      aux_sym_content_token1,
      anon_sym_LT_SLASH,
      aux_sym_html_entity_token1,
      aux_sym_html_entity_token2,
      aux_sym_html_entity_token3,
      sym_twig_comment,
      anon_sym_LBRACE_LBRACE,
  [808] = 4,
    ACTIONS(182), 1,
      anon_sym_GT,
    ACTIONS(184), 1,
      anon_sym_SLASH_GT,
    ACTIONS(186), 1,
      sym_html_attribute_name,
    STATE(44), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [822] = 3,
    ACTIONS(190), 1,
      sym_html_attribute_name,
    ACTIONS(188), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [834] = 4,
    ACTIONS(182), 1,
      anon_sym_GT,
    ACTIONS(186), 1,
      sym_html_attribute_name,
    ACTIONS(193), 1,
      anon_sym_SLASH_GT,
    STATE(45), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [848] = 4,
    ACTIONS(186), 1,
      sym_html_attribute_name,
    ACTIONS(195), 1,
      anon_sym_GT,
    ACTIONS(197), 1,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [862] = 4,
    ACTIONS(186), 1,
      sym_html_attribute_name,
    ACTIONS(195), 1,
      anon_sym_GT,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [876] = 3,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      sym_html_attribute_name,
    STATE(51), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [887] = 3,
    ACTIONS(203), 1,
      sym_html_attribute_name,
    ACTIONS(205), 1,
      anon_sym_GT,
    STATE(51), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [898] = 4,
    ACTIONS(207), 1,
      sym_html_attribute_value,
    ACTIONS(209), 1,
      anon_sym_DQUOTE,
    ACTIONS(211), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      sym_html_quoted_attribute_value,
  [911] = 3,
    ACTIONS(203), 1,
      sym_html_attribute_name,
    ACTIONS(213), 1,
      anon_sym_GT,
    STATE(46), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [922] = 4,
    ACTIONS(215), 1,
      sym_html_attribute_value,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      sym_html_quoted_attribute_value,
  [935] = 3,
    ACTIONS(188), 1,
      anon_sym_GT,
    ACTIONS(221), 1,
      sym_html_attribute_name,
    STATE(51), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [946] = 3,
    ACTIONS(203), 1,
      sym_html_attribute_name,
    ACTIONS(224), 1,
      anon_sym_GT,
    STATE(47), 2,
      sym_html_attribute,
      aux_sym_style_start_tag_repeat1,
  [957] = 2,
    ACTIONS(228), 1,
      anon_sym_EQ,
    ACTIONS(226), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [966] = 1,
    ACTIONS(230), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [972] = 1,
    ACTIONS(232), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_html_attribute_name,
  [978] = 3,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(234), 1,
      sym_raw_text,
    STATE(24), 1,
      sym_html_end_tag,
  [988] = 3,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(236), 1,
      sym_raw_text,
    STATE(25), 1,
      sym_html_end_tag,
  [998] = 3,
    ACTIONS(238), 1,
      sym__start_tag_name,
    ACTIONS(240), 1,
      sym__style_start_tag_name,
    ACTIONS(242), 1,
      sym__script_start_tag_name,
  [1008] = 2,
    ACTIONS(244), 1,
      anon_sym_EQ,
    ACTIONS(226), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [1016] = 1,
    ACTIONS(246), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1021] = 2,
    ACTIONS(248), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(250), 1,
      sym_variable,
  [1028] = 1,
    ACTIONS(252), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1033] = 1,
    ACTIONS(254), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1038] = 2,
    ACTIONS(256), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(258), 1,
      sym__interpolation_content,
  [1045] = 2,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_html_end_tag,
  [1052] = 2,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    STATE(9), 1,
      sym_html_end_tag,
  [1059] = 1,
    ACTIONS(260), 2,
      anon_sym_PERCENT_RBRACE,
      sym_variable,
  [1064] = 1,
    ACTIONS(230), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [1069] = 1,
    ACTIONS(232), 2,
      anon_sym_GT,
      sym_html_attribute_name,
  [1074] = 2,
    ACTIONS(262), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(264), 1,
      sym__interpolation_content,
  [1081] = 1,
    ACTIONS(266), 2,
      anon_sym_PERCENT_RBRACE,
      sym_variable,
  [1086] = 2,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_arguments,
  [1093] = 1,
    ACTIONS(270), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1098] = 2,
    ACTIONS(248), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(272), 1,
      sym_variable,
  [1105] = 1,
    ACTIONS(274), 1,
      anon_sym_GT,
  [1109] = 1,
    ACTIONS(276), 1,
      ts_builtin_sym_end,
  [1113] = 1,
    ACTIONS(278), 1,
      anon_sym_RBRACE_RBRACE,
  [1117] = 1,
    ACTIONS(280), 1,
      anon_sym_GT,
  [1121] = 1,
    ACTIONS(282), 1,
      anon_sym_PERCENT_RBRACE,
  [1125] = 1,
    ACTIONS(284), 1,
      sym__start_tag_name,
  [1129] = 1,
    ACTIONS(286), 1,
      anon_sym_PERCENT_RBRACE,
  [1133] = 1,
    ACTIONS(288), 1,
      sym__doctype,
  [1137] = 1,
    ACTIONS(290), 1,
      aux_sym_html_doctype_token1,
  [1141] = 1,
    ACTIONS(292), 1,
      sym_erroneous_end_tag_name,
  [1145] = 1,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1149] = 1,
    ACTIONS(296), 1,
      anon_sym_GT,
  [1153] = 1,
    ACTIONS(298), 1,
      aux_sym_html_quoted_attribute_value_token1,
  [1157] = 1,
    ACTIONS(300), 1,
      aux_sym_html_quoted_attribute_value_token2,
  [1161] = 1,
    ACTIONS(302), 1,
      anon_sym_DQUOTE,
  [1165] = 1,
    ACTIONS(302), 1,
      anon_sym_SQUOTE,
  [1169] = 1,
    ACTIONS(304), 1,
      anon_sym_PERCENT_RBRACE,
  [1173] = 1,
    ACTIONS(306), 1,
      anon_sym_RBRACE_RBRACE,
  [1177] = 1,
    ACTIONS(308), 1,
      anon_sym_PERCENT_RBRACE,
  [1181] = 1,
    ACTIONS(310), 1,
      anon_sym_PERCENT_RBRACE,
  [1185] = 1,
    ACTIONS(312), 1,
      anon_sym_GT,
  [1189] = 1,
    ACTIONS(314), 1,
      sym__end_tag_name,
  [1193] = 1,
    ACTIONS(316), 1,
      anon_sym_DQUOTE,
  [1197] = 1,
    ACTIONS(316), 1,
      anon_sym_SQUOTE,
  [1201] = 1,
    ACTIONS(318), 1,
      sym__end_tag_name,
  [1205] = 1,
    ACTIONS(320), 1,
      aux_sym_html_quoted_attribute_value_token1,
  [1209] = 1,
    ACTIONS(322), 1,
      aux_sym_html_quoted_attribute_value_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 55,
  [SMALL_STATE(4)] = 110,
  [SMALL_STATE(5)] = 152,
  [SMALL_STATE(6)] = 194,
  [SMALL_STATE(7)] = 236,
  [SMALL_STATE(8)] = 278,
  [SMALL_STATE(9)] = 315,
  [SMALL_STATE(10)] = 331,
  [SMALL_STATE(11)] = 347,
  [SMALL_STATE(12)] = 363,
  [SMALL_STATE(13)] = 379,
  [SMALL_STATE(14)] = 395,
  [SMALL_STATE(15)] = 411,
  [SMALL_STATE(16)] = 427,
  [SMALL_STATE(17)] = 443,
  [SMALL_STATE(18)] = 459,
  [SMALL_STATE(19)] = 475,
  [SMALL_STATE(20)] = 491,
  [SMALL_STATE(21)] = 507,
  [SMALL_STATE(22)] = 523,
  [SMALL_STATE(23)] = 539,
  [SMALL_STATE(24)] = 555,
  [SMALL_STATE(25)] = 571,
  [SMALL_STATE(26)] = 587,
  [SMALL_STATE(27)] = 603,
  [SMALL_STATE(28)] = 626,
  [SMALL_STATE(29)] = 640,
  [SMALL_STATE(30)] = 654,
  [SMALL_STATE(31)] = 668,
  [SMALL_STATE(32)] = 682,
  [SMALL_STATE(33)] = 696,
  [SMALL_STATE(34)] = 710,
  [SMALL_STATE(35)] = 724,
  [SMALL_STATE(36)] = 738,
  [SMALL_STATE(37)] = 752,
  [SMALL_STATE(38)] = 766,
  [SMALL_STATE(39)] = 780,
  [SMALL_STATE(40)] = 794,
  [SMALL_STATE(41)] = 808,
  [SMALL_STATE(42)] = 822,
  [SMALL_STATE(43)] = 834,
  [SMALL_STATE(44)] = 848,
  [SMALL_STATE(45)] = 862,
  [SMALL_STATE(46)] = 876,
  [SMALL_STATE(47)] = 887,
  [SMALL_STATE(48)] = 898,
  [SMALL_STATE(49)] = 911,
  [SMALL_STATE(50)] = 922,
  [SMALL_STATE(51)] = 935,
  [SMALL_STATE(52)] = 946,
  [SMALL_STATE(53)] = 957,
  [SMALL_STATE(54)] = 966,
  [SMALL_STATE(55)] = 972,
  [SMALL_STATE(56)] = 978,
  [SMALL_STATE(57)] = 988,
  [SMALL_STATE(58)] = 998,
  [SMALL_STATE(59)] = 1008,
  [SMALL_STATE(60)] = 1016,
  [SMALL_STATE(61)] = 1021,
  [SMALL_STATE(62)] = 1028,
  [SMALL_STATE(63)] = 1033,
  [SMALL_STATE(64)] = 1038,
  [SMALL_STATE(65)] = 1045,
  [SMALL_STATE(66)] = 1052,
  [SMALL_STATE(67)] = 1059,
  [SMALL_STATE(68)] = 1064,
  [SMALL_STATE(69)] = 1069,
  [SMALL_STATE(70)] = 1074,
  [SMALL_STATE(71)] = 1081,
  [SMALL_STATE(72)] = 1086,
  [SMALL_STATE(73)] = 1093,
  [SMALL_STATE(74)] = 1098,
  [SMALL_STATE(75)] = 1105,
  [SMALL_STATE(76)] = 1109,
  [SMALL_STATE(77)] = 1113,
  [SMALL_STATE(78)] = 1117,
  [SMALL_STATE(79)] = 1121,
  [SMALL_STATE(80)] = 1125,
  [SMALL_STATE(81)] = 1129,
  [SMALL_STATE(82)] = 1133,
  [SMALL_STATE(83)] = 1137,
  [SMALL_STATE(84)] = 1141,
  [SMALL_STATE(85)] = 1145,
  [SMALL_STATE(86)] = 1149,
  [SMALL_STATE(87)] = 1153,
  [SMALL_STATE(88)] = 1157,
  [SMALL_STATE(89)] = 1161,
  [SMALL_STATE(90)] = 1165,
  [SMALL_STATE(91)] = 1169,
  [SMALL_STATE(92)] = 1173,
  [SMALL_STATE(93)] = 1177,
  [SMALL_STATE(94)] = 1181,
  [SMALL_STATE(95)] = 1185,
  [SMALL_STATE(96)] = 1189,
  [SMALL_STATE(97)] = 1193,
  [SMALL_STATE(98)] = 1197,
  [SMALL_STATE(99)] = 1201,
  [SMALL_STATE(100)] = 1205,
  [SMALL_STATE(101)] = 1209,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_element_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_directive, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_directive, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_self_closing_tag, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_self_closing_tag, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vue_interpolation, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vue_interpolation, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_entity, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_entity, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vue_interpolation, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vue_interpolation, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_self_closing_tag, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_self_closing_tag, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_doctype, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_doctype, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0), REDUCE(sym_html_void_tag, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0), REDUCE(sym_html_void_tag, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attribute, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attribute, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_quoted_attribute_value, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_statement, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [276] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_statement, 2, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__style_start_tag_name = 1,
  ts_external_token__script_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token__interpolation_content = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token__interpolation_content] = sym__interpolation_content,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_content] = true,
  },
  [2] = {
    [ts_external_token__implicit_end_tag] = true,
  },
  [3] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [4] = {
    [ts_external_token_raw_text] = true,
  },
  [5] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
  },
  [6] = {
    [ts_external_token__interpolation_content] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
  },
  [8] = {
    [ts_external_token_erroneous_end_tag_name] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_shopware_twig_external_scanner_create(void);
void tree_sitter_shopware_twig_external_scanner_destroy(void *);
bool tree_sitter_shopware_twig_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_shopware_twig_external_scanner_serialize(void *, char *);
void tree_sitter_shopware_twig_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shopware_twig(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_shopware_twig_external_scanner_create,
      tree_sitter_shopware_twig_external_scanner_destroy,
      tree_sitter_shopware_twig_external_scanner_scan,
      tree_sitter_shopware_twig_external_scanner_serialize,
      tree_sitter_shopware_twig_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "shopware_twig",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
